### ISSUE TITLE
Any interest in expanding this to also configure color themes?

### ISSUE THREAD

**Issue by PerryCodes** [braver/programmingfonts#101]
Of course there is https://studiostyl.es/ for viewing/downloading color themes for older versions of Visual Studio.

But I don't really know of a site that lets you quickly/easily play around with different color combinations and/or build your own.  That doesn't mean there isn't one out there somewhere... if you happen to know of one, please let me know!

Any chance of implementing something like this on top of the Programming Fonts site?

**Comment by braver** [comment]
No, not really. I already try to include all default color schemes for CodeMirror, which is quite a list already. But color schemes are specific to the editor they’re built for. It’s impossible to preview a VS Code color scheme without VS Code.

The focus here is on fonts though, the colors are just there to play with and because it’s super easy to do. And because fonts look different in different colors of course. But I don’t want to expand the scope in any way, especially not away from fonts.
