### ISSUE TITLE
Fira Code render wrong font

### ISSUE THREAD

**Issue by gmtborges** [braver/programmingfonts#132]
Fira Code is not using the right font, because Fira Code has slashed zero. And the current version is using dotted zero.

**Comment by waldyrious** [comment]
Hm, it does seem to be Fira Code indeed — at least the "firacode" font used by the website. I used Firefox's developer tools to make a couple experiments on the website to verify this:
- I removed everything from the HTML body but a div containing the code sample including the zero, and verified that Firefox reports it as using the Fira Code font exclusively;
- then I added a Unicode character to the div that I know that Fira Code doesn't have (`∀`) and confirmed that for that particular character the browser reports a different font being used as the fallback
- this means that if the zero was being served by a different font, Firefox would have detected it.

Recording of the above:

![621UZ2F3Dz](https://user-images.githubusercontent.com/478237/233756510-f06bd6e3-9906-4e28-841e-00f313d53cdf.gif)

So what may be happening here is the Fira Code font used in the website having been built with (or customized via [CSS OpenType features](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Fonts/OpenType_fonts_guide) — see #94) the dotted zero variant, which the font supports [since v2.0](https://github.com/tonsky/FiraCode/blob/6.2/CHANGELOG.md?plain=1#L190), from September 2019. I'm sure @braver would be able to provide more concrete information, though.

**Comment by waldyrious** [comment]
Hmm, interestingly, though, using the website's "zero style" filter seems to imply that there's only a dotted zero version of Fira Code in the site. In particular, setting the filter to the "slashed zero" removes Fira Code from the font list altogether.

(On a separate note, @braver: the behavior of the filter is quite puzzling at first, because if the currently selected font doesn't conform to the filter, it disappears from the list, but the code sample doesn't change at all. Maybe the textarea should get emptied, or greyed out until one selects a font from the filtered list?)

**Comment by braver** [comment]
The current version (6.2) of FiraCode uses a slashed zero. This seems to have changed in [version 2](https://github.com/tonsky/FiraCode/releases/tag/2). I'm not sure how long ago our entry here was updated last. fed7059 corrects that.

**Comment by braver** [comment]
@waldyrious The currently active font is marked both in the list and in the footer. Indeed, any search query could make the active font disappear from the list and make it less clear which font is currently being rendered. I've been thinking about reserving more space in the UI to display the current font and some of its info, that would also make the interaction with search more obvious (separates the search list from the currently active font). Haven't thought of something that would be as minimal as the current design though, and it hasn't been a big priority.
