### ISSUE TITLE
Add font: MonoLisa

### ISSUE THREAD

**Issue by MarcusSterz** [braver/programmingfonts#148]
- What's it called?
MonoLisa
You may find it interesting since MonoLisa provides italics, ligatures and variable versions. Also it has the most extensive range of languages covered. 

- Where did you find it? Preferably the website of the creator of the font.
I am the designer, here’s the website: https://www.monolisa.dev/

- Where can we download it?
https://www.monolisa.dev/buy
If you cannot afford it, I can provide a copy.

- What's the license?
https://www.monolisa.dev/license

**Comment by braver** [comment]
Thanks!

The personal license would indeed allow us to include MonoLisa on the site. I did not want to take on that expense personally, but if you want to share your copy for this purpose that would be awesome.

I made a temporary email address where you can reach me, so that you don’t have to share any files publicly through GitHub or anything: nuttig-doorgaand.04@icloud.com

Alternatively, you can make a PR that includes the required file (hopefully they deliver some woff files for use in websites like this).
