### ISSUE TITLE
Add font: HyperFont

### ISSUE THREAD

**Issue by pirj** [braver/programmingfonts#161]
Information we need about new fonts:
- What's it called? HyperFont https://en.wikipedia.org/wiki/HyperFont
- Where did you find it? https://www.lowing.org/fonts/
- Where can we download it? https://www.fontpalace.com/font-details/HyperFont/
- What's the license? **Unknown** "font developed in 1993 by Hilgraeve Inc. to be used by the [HyperTerminal](https://en.wikipedia.org/wiki/HyperTerminal) [terminal emulation](https://en.wikipedia.org/wiki/Terminal_emulation) application program included in [Microsoft Windows](https://en.wikipedia.org/wiki/Microsoft_Windows)." 😬

**Comment by braver** [comment]
Since Hilgraeve Inc. is an existing commercial entity and their HyperTerminal an existing commercial product, I kind of doubt the license allows usage of that font. It doesn't look like it's offered separately (that I could find), so what probably happened is that some folks extracted the font and then it started to wander around the world of "free fonts" websites.

**Comment by braver** [comment]
I can't find the font provided on its own via Hilgraeve's website. It very much looks like a font extracted from a commercial product. Without confirmation of the licensing terms I can't include it.
