### ISSUE TITLE
Please add quite a lot of non-ASCII characters to the listing

### ISSUE THREAD

**Issue by phmarek** [braver/programmingfonts#33]
For those who like to use that font to produce technical documentation it is very important that the font includes non-ASCII symbols as well. Starting with greek characters (α, β, γ, the famous λ ;), to typographical notation (em-dash —), mathematics (≅, ≠, ≤, ≥), line drawing (←→⇐⇒) and so on and on...

So, for things like this perhaps some LaTeX or markdown document might be a better choice for the "source".

Thank you very much!

**Comment by AllanLRH** [comment]
Or just add those characters as a comment in the current snippet, which also states the purpose of the comment (to show how those characters are rendered).

**Comment by justdmitry** [comment]
You can type/paste your text directly into right pane

**Comment by braver** [comment]
<img width="269" alt="screen shot 2019-01-21 at 19 32 43" src="https://user-images.githubusercontent.com/2543659/51492815-5beb2780-1db3-11e9-9ef1-08b6c54effdd.png">

Perhaps it's not 100% super crystal clear, but rather than trying to cater towards everyone's ideas of what to put in the right hand pane, you can edit it to your wishes.
