### ISSUE TITLE
Add font: B612

### ISSUE THREAD

**Issue by pocra** [braver/programmingfonts#35]
https://github.com/polarsys/b612

**Comment by braver** [comment]
That's a neat font! I'll have to look into this one. Is it monospace though?

-----
It's kind of a rule that the fonts need to be monospace. Of course you can code in whatever font you like, and proportional fonts are good and legible, but I need to limit the list somehow. Otherwise it would just be a list of all the worlds fonts :)

**Comment by pocra** [comment]
Yes, there is also a mono space font style.

![monospace sample from an airbus](https://www.amc-archi.com/mediatheque/2/2/6/000036622_large/typographie-open-source-b612-the-polarsys-font.jpeg "monospace sample from an airbus")

**Comment by braver** [comment]
Whooo!

**Comment by braver** [comment]
Got it now!
