### ISSUE TITLE
APL2741 now has ligatures.

### ISSUE THREAD

**Issue by pupitetris** [braver/programmingfonts#82]
You got it marked as not supporting ligatures. Thanks, great site.

**Comment by braver** [comment]
Oh, that's cool. Where can I get that version?

**Comment by pupitetris** [comment]
I saw it on your site, but I double-checked on a Windows machine and it's not there.

So I went back to Linux and what I see is that Linux (Firefox 80.0 with Ubuntu 20.04) can't render that font, for some reason. So, you are asking for "font-family: apl3741, monospace" and since that font won't load, it falls back to monospace, which I had set on my browser as Iosevka.

I wonder if there's a way of notifying users that a given font wasn't able to load...

**Comment by braver** [comment]
> I wonder if there's a way of notifying users that a given font wasn't able to load...

Well if it fails to load that might be possible, but if the rendering system decides it cannot use the font and falls back to another font.. I don't think we can know that that happens. FYI, what happens all the time is that one font is missing a character, and then takes the character from the next font in line. I can probably do something like make the error more obvious by setting "serif" as the fallback font instead of "monospace". 

Ideally though, it should never happen. Have you tried downloading APL2741 on your Linux machine and trying to install it? Maybe that yields more useful information about why it doesn't work.
