### ISSUE TITLE
Support for Smartphones and make the sidebar collapsible.

### ISSUE THREAD

**Issue by zoomlogo** [braver/programmingfonts#93]
Let me clear up, when I try to use the website in a smartphone, the backspace and enter key dont remove the `\n` char and have issues with appending `\n` char respectively. 

Also the side bar (where you select the font) occupies most of the space, maybe make it collapsible?

**Comment by braver** [comment]
Sorry, but "works on my machine" I'm afraid. The code editing area uses [CodeMirror](https://codemirror.net). Nothing about how that works is something I can fix, so any bugs you experience are better reported with them. 

I have no intention of making the sidebar collapsible. The core functionality here is to find and compare fonts. On most devices the editing area is large enough to do so and many enter some code of your own. 

Maybe you can show me a screenshot of what it looks like on your smartphone, so that I can get a better picture of what you're experiencing?

**Comment by zoomlogo** [comment]
@braver closing because I found a temporary solution.


About the sidebar, I dont care that much.

About the backspace problem, in Chrome there is an option under the upper right 3 dots button, it is __Desktop Site__ .
Just click it, the site reloads and the backspace and enter are working.


Thanks for the great website.👍
